function dAdt = update_particle_algae(particle, S, T, chl, light)    dAdt = get_algae_collisions(particle, S, T, chl) + ...           get_algae_growth(particle, chl, light) + ...           get_algae_mortality(particle) + ...           get_algae_respiration(particle, T);           
endfunction  
